---
spring:
  profiles: server
  application:
    name: server
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
---
spring:
  profiles: client
  application:
    name: client

server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1

hystrix.command.default:
  circuitBreaker.requestVolumeThreshold: 5 # default 20
  execution.isolation.thread.timeoutInMilliseconds: 3000 # default 1000

