server:
  port: 9001

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://C:/Users/adaml/projects/spring-cloud/spring-cloud-examples/
          search-paths: 05-config-server/config-repository
    bus:
      trace:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
