---
# standalone eureka server
# http://cloud.spring.io/spring-cloud-static/Camden.SR3/#_standalone_mode
spring:
  profiles: default
  application.name: eureka-server
server:
  port: 7001
eureka:
  client:
    # In standalone mode, you might prefer to switch off the client side behaviour,
    # so it doesn’t keep trying and failing to reach its peers.
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
  server:
    eviction-interval-timer-in-ms: 10000
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
---
spring:
  profiles: eureka-server-1
  application.name: eureka-server-1
server:
  port: 7001
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:7002/eureka/
  server:
    eviction-interval-timer-in-ms: 10000
---
spring:
  profiles: eureka-server-2
  application.name: eureka-server-2
server:
  port: 7002
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:7001/eureka/
  server:
    eviction-interval-timer-in-ms: 10000
