---
# standalone eureka server
# http://cloud.spring.io/spring-cloud-static/Brixton.SR5/#_standalone_mode
spring:
  profiles: default
  application.name: eureka-server
server:
  port: 9000
eureka:
  client:
    # In standalone mode, you might prefer to switch off the client side behaviour,
    # so it doesn’t keep trying and failing to reach its peers.
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9000/eureka/

---
spring:
  profiles: eureka-server-1
  application.name: eureka-server-1
server:
  port: 9001
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:9002/eureka/

---
spring:
  profiles: eureka-server-2
  application.name: eureka-server-2
server:
  port: 9002
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:9001/eureka/