---
spring:
  profiles: server
  application:
    name: eureka-client-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 1
server:
  port: 8001
---
spring:
  profiles: client
  application:
      name: eureka-client-client
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 1