---
spring:
  profiles: server
  application:
    name: server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
server:
  port: 9001
---
spring:
  profiles: client
  application:
      name: client
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1